### ISSUE TITLE
Download video to Device: external SD

### ISSUE THREAD

**Issue by ppgb** [NineWorlds/serenity-android#189]
When I click "Download Video to Device" the folder it shows is /mnt/sdcard
which is the internal memory where the application sits.

I want to store the file to the External SD card, which is /mnt/external_sd/

I can't find a way to navigate from /mnt/sdcard to /mnt/ I even tried the back arrow but it did not work. Ideas?

[edit] same as Issue #90 Good to see I have consistent needs, but this is becoming more pressing as my device's internal memory is full and the free space is on my external SD! So I can download to Device only if I can point Serenity to the external SD.

**Comment by kingargyle** [comment]
Out of scope for 2.0.0.
