### ISSUE TITLE
Better Mobility and Visibility

### ISSUE THREAD

**Issue by goosar19** [NineWorlds/serenity-android#235]
I do apologize if i should have created another issue for the multiple suggestions.

I like the option of the tiles instead of the details option when viewing movies and tv shows but not everyone has adopted the 50"+ tvs yet. Perhaps there could be a large and small tile option?  My suggestion would be for 2 tiles high rater than 3.

I also think navigation would be easier if the categories menu, including the recently watched and on deck, was persistant or fixed.  It would look neat graphically if you could get it to autohide when you move away from it.

The last suggestion is also about navigation.  At the bottom of the screen, like underneath the banners in detail mode and below the tiles in tile view, a selectable alphabet for quicker navigation.  I enjoy the detail view but to scroll through 600 movies to find something you are looking for could be made easier.

Of course I would hope that any of these suggestion you may incorporate toggleable, leaving the current interface available for those that like it.

**Comment by kingargyle** [comment]
Closing this for now as it isn't a priority for 2.0.0.
