### ISSUE TITLE
Issues with last played position sync between Serenity (using MX Player) and Plex

### ISSUE THREAD

**Issue by ppgb** [NineWorlds/serenity-android#245]
Hi,

It's been a while since I last used Serenity, but I noticed that the sync of the last play position is not working perfectly well.

It kind of works half way. When I launch from Serenity, it will play from the last played position 12:03 known to Plex. I then pause MX Player at 14:32 and come back to Serenity.

I then play the same file on Plex for Android, it does play from 14:32. GREAT!! 

I then pause Plex for Android at 18:48. I then come back to Serenity and press "Play", I expect it to resume from 18:48 but MX Player actually starts the playback at 14:32 for some reason.

If I then launch the video in Plex Web and not Serenity, it picks up from 18:48 and not 14:32 like Serenity. So Plex seems to be aware of the 18:48 position. 

Can you reproduce the issue?

I run the latest version of everything (PMS, Serenity, Plex for Android).

**Comment by kingargyle** [comment]
External players no longer supported, in favor of internal exoplayer.
