### ISSUE TITLE
StackOverflowError in TwoWayAbsListView.dispatchDraw

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#293]
I just built and installed 1.9.1 and I'm getting a StackOverflowError when I browse my TV shows in a Grid layout.

The exception happens when I move the selection all the way right till it scrolls the show list over.

I added some debug info to help understand what is happening. The problem is that the code creates a deep view hierarchy that looks like this:

01-11 22:56:03.003  9633  9633 I Alon    :  RelativeLayout 1750466472
01-11 22:56:03.003  9633  9633 I Alon    :    FrameLayout
01-11 22:56:03.003  9633  9633 I Alon    :     FrameLayout
01-11 22:56:03.003  9633  9633 I Alon    :      FrameLayout
01-11 22:56:03.003  9633  9633 I Alon    :       FrameLayout
...
01-11 22:56:03.003  9633  9633 I Alon    :                                          RoundedImageView 1727695752
01-11 22:56:03.003  9633  9633 I Alon    :                                          BadgeView 1750628936
...
01-11 22:56:03.007  9633  9633 I Alon    :     BadgeView 1750262360
01-11 22:56:03.007  9633  9633 I Alon    :    BadgeView 1750259296
01-11 22:56:03.007  9633  9633 I Alon    :   ImageView 1737185736
01-11 22:56:03.007  9633  9633 I Alon    :   ProgressBar 1745227000

The exception looks like this:

01-11 22:56:03.023  9633  9633 E AndroidRuntime: FATAL EXCEPTION: main
01-11 22:56:03.023  9633  9633 E AndroidRuntime: java.lang.StackOverflowError
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.graphics.Matrix.preRotate(Matrix.java:204)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.View.updateMatrix(View.java:5881)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.View.hasIdentityMatrix(View.java:5857)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:2455)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2323)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:2716)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2323)
...
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:2716)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2323)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.View.draw(View.java:9379)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:2718)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2323)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at com.jess.ui.TwoWayAbsListView.dispatchDraw(TwoWayAbsListView.java:1626)
01-11 22:56:03.023  9633  9633 E AndroidRuntime:        at android.view.View.draw(View.java:9

I've narrowed it down a bit but I still don't know what the fix is:
TVShowBannerImageGalleryAdapter.java:172 Creates a BadgeView with a target that is an ImageView. 

BadgeView#init() calls applyTo() which has an else fork that happens when target is not a TabWidget.
In this fork,  it adds a newly created FrameLayout to the targets parent which is FrameLayout. This keeps happening over and over and builds a deep nesting.

Not exactly sure why yet.

Running on a Sony BRP (original model).

**Comment by alonalbert** [comment]
OK, I think I know what the problem is:
TVShowPosterImageGalleryAdapter.getView() uses convertView which already had it's ImageView re-parented and it reparents it again, deeper in the hierarchy.

**Comment by kingargyle** [comment]
Okay. Instead of re-using the convert view, which we could just tell it to create a new view.  Which should then fix that issue.   Evetually, I want to replace the Gallery view with the following.

https://github.com/NineWorlds/HorizontalVariableListView

If you want to make the pull request with the change to not reuse the convert view, I can get it merged into the 1.9.2 development branch.

**Comment by alonalbert** [comment]
I'm testing exactly that change right now :)

**Comment by alonalbert** [comment]
Tested OK.

It's been a while since I worked with Github and I don't remember how to sync my repository etc.

I created a patch instead:

-----%<----------------------------------------------------------------------
diff --git a/serenity-app/src/main/java/us/nineworlds/serenity/ui/browser/tv/TVShowPosterImageGalleryAdapter.java b/serenity-app/src/main/java/us/nineworlds/serenity/ui/browser/tv/TVShowPosterImageGalle
index 30ae5fe..a4f9c47 100644
--- a/serenity-app/src/main/java/us/nineworlds/serenity/ui/browser/tv/TVShowPosterImageGalleryAdapter.java
+++ b/serenity-app/src/main/java/us/nineworlds/serenity/ui/browser/tv/TVShowPosterImageGalleryAdapter.java
@@ -57,11 +57,8 @@ TVShowBannerImageGalleryAdapter {
         */
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
-               View galleryCellView = convertView;
-               if (galleryCellView == null) {
-                       galleryCellView = showActivity.getLayoutInflater().inflate(
-                                       R.layout.poster_tvshow_indicator_view, null);
-               }
+               View galleryCellView = showActivity.getLayoutInflater().inflate(
+                               R.layout.poster_tvshow_indicator_view, null);
 
                SeriesContentInfo pi = tvShowList.get(position);
 
-----%<----------------------------------------------------------------------

**Comment by kingargyle** [comment]
For github, all you need to do is create a branch with your changes, push your branch to your github repo, and then in Github, you'll have an item to Submit a pull request.

I'd prefere a pull request as I can comment inline with any changes.  I suspect i'll need to make similar changes to the the Movie browser and episode browsers as well.

Regardless I'll try and get this changed merged in a day or two.

**Comment by alonalbert** [comment]
My develop branch is out of sync. I synced it but it's 6 commits ahead of your develop branch and I don't know how to fix it.

Sorry, my GIT sucks.

**Comment by kingargyle** [comment]
Looks like it worked alright.  So I merged the pull request.  Going to close this issue.  Thanks for the fix.
