### ISSUE TITLE
Feature Request: Support Remote Servers 

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#295]
Plex supports remote connections https://my.plexapp.com.

One can retrieve a token from https://my.plexapp.com/users/sign_in.xml:

and use it to access servers from:

https://my.plexapp.com/pms/servers?X-Plex-Token=<token>

Or actual sections from:

https://my.plexapp.com/pms/system/library/sections?X-Plex-Token=<token>

The token can be passed as either a URL parameter or a connection header.

I have built a hard coded binary that connects remotely to my system.

Sample code that gets the auth token:

  public static String authenticate(String username, String password)
      throws IOException, SAXException {
    String auth = username + ":" + password;
    String encoded = Base64.encodeToString(auth.getBytes(), Base64.NO_WRAP);
    return authenticate(encoded);
  }

  public static String authenticate(String encoded)
      throws IOException, SAXException {
    final URL url = new URL(MY_PLEX_AUTH_URL);
    final HttpURLConnection connection = (HttpURLConnection) url.openConnection();
    try {
      connection.setRequestMethod("POST");
      connection.setRequestProperty("Authorization", "Basic " + encoded);
      connection.setRequestProperty("X-Plex-Client-Identifier", "Test");
      final InputStream in = connection.getInputStream();
      final Document document = sDocumentBuilder.parse(in);
      return document.getDocumentElement().getAttribute("authenticationToken");
    } finally {
      if (connection != null) {
        connection.disconnect();
      }
    }
  }

My hard coded build consists of:
- Replacing ResourcePaths.getHostPort() with a hard coded <public-ip-address>:<port> of my server
- Patch getImageURL() to replace the correct hostname
- Add HTTP Request Header  X-Plex-Token to various places:
  - OKHttpImageLoader.getStreamFromNetwork()
  -  PlexappFactory.requestSuccessful()
  -  PlexappFactory.serializeResource()
  - VolleyUtils.volleyXmlGetRequest()

It doesn't quite work, there's a few places missing - most notably, the media stream itself is still unauthorized but it's a start.

**Comment by kingargyle** [comment]
I'm going to be adding support for Mediabrowser.tv, and will be doing some refactoring around this to allow for user signins.   I'd like to see if we can do some dependency injection, and maybe extend the Servers interface to hold the necessary information regarding that particular server.   With the new Universal Transcoder, Plex has removed the requirement to have an APIKey to do transcoding, so making My Plex and Plexconnect more viable options,

**Comment by kingargyle** [comment]
Plex remote servers, not happening.  Emby Remote servers, maybe in a future release.
