### ISSUE TITLE
Play Button Now Pauses

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#296]
This CL:

https://github.com/NineWorlds/serenity-android/commit/a9c48f36768192075e472a5de915b52a417ffa01

Reverts a change I did long ago - the one that makes Play button not function exactly as Pause but rather, as a real Play button.

Was this on purpose? The CL description suggests it was just adding tests. Did this accidentally get reverted?

**Comment by kingargyle** [comment]
It was probably accidently lost when I was doing some coding refactoring I had done.  I'll try and get this back in with a test.

**Comment by kingargyle** [comment]
@alonalbert I'm sorry for the long delay.  The develop branch should have the functionality restored for the play button.  Please let me know if it is still not working.

**Comment by kingargyle** [comment]
Should be working again target to be included in 1.9.5
