### ISSUE TITLE
Subtitles Format is Empty but Codec Has Relevant Information

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#297]
Subtitles downloaded with the OpenSubtitles plugin have a an empty format field but seem to have a new codec filed that has the relevant information.

<Stream id="215415" key="/library/streams/215415" streamType="3" codec="srt" language="English" languageCode="eng" format=""/>

To compare, the same subtitle downloaded directly as a file results in:

<Stream id="215414" key="/library/streams/215414" streamType="3" codec="srt" format="srt"/>

Using Codec instead of Format would work but perhaps code should check for both, for backwards compatibility.

**Comment by kingargyle** [comment]
Targeting this as part of the Subtitle rework leveraging the support provided by ExoPlayer.
