### ISSUE TITLE
Feature Request: Enable Subtitles While Playing a Video

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#299]
Add a hard key that will cycle through all available subtitles while a video is playing. Maybe KEYCODE_U?

**Comment by kingargyle** [comment]
With the way the current remotes have gone to fewer keys or keyboards on remotes, I'll probably have to have an option on the UI to allow changing which subtitle is playing.   With the app now using Exoplayer this is an easier option as ExoPlayer handles displaying of any subtitles

**Comment by kingargyle** [comment]
will implement this in 3.0, #401
