### ISSUE TITLE
Feature Request: Add Ability to Sync Subtitles

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#300]
Subtitles are often out of sync. How about adding hard keys that add/subtract 1s of sync delay.

Popcorn time does this, it's very nice.
https://popcorntime.uservoice.com/forums/245422-general/suggestions/5825352-manual-subtitles-sync

H – Increase subtitle offset by 0.1 seconds
G – Decrease subtitle offset by 0.1 seconds
Shift+H – Increase subtitle offset by 1 second
Shift+G – Decrease subtitle offset by 1 second
Ctrl+H – Increase subtitle offset by 5 seconds
Ctrl+G – Decrease subtitle offset by 5 seconds

**Comment by kingargyle** [comment]
We also need a way to do this for those that don't have keyboards attached.  Maybe an on screen display that can adjust the timing?
