### ISSUE TITLE
NPE in SerenitySurfaceViewVideoActivity

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#303]
Device: Sony Google TV BRP
To reproduce:

Play something.
While playing, switch to a different app or Live TV
Switch back to Serenity
Screen will be black
Press Back on remote
Crash

09-08 09:32:13.219  3826  3826 E AndroidRuntime: java.lang.NullPointerException
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at us.nineworlds.serenity.ui.video.player.SerenitySurfaceViewVideoActivity.onBackPressed(SerenitySurfaceViewVideoActivity.java:346)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at us.nineworlds.serenity.ui.video.player.SerenitySurfaceViewVideoActivity.onKeyDown(SerenitySurfaceViewVideoActivity.java:361)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.view.KeyEvent.dispatch(KeyEvent.java:2635)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.app.Activity.dispatchKeyEvent(Activity.java:2308)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at com.android.internal.policy.impl.tv.TvWindow$DecorView.dispatchKeyEvent(TvWindow.java:1137)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.view.ViewRoot.deliverKeyEventPostIme(ViewRoot.java:2946)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2916)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.view.ViewRoot.handleMessage(ViewRoot.java:2093)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:132)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:4196)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:491)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
09-08 09:32:13.219  3826  3826 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)

**Comment by kingargyle** [comment]
I bet something isn't being injected again when the activity is recreated.

**Comment by kingargyle** [comment]
Closing as much of this code has been entirely rewritten in the 2.x implementation.
