### ISSUE TITLE
Hard to Tell What Episode is Currently Playing

### ISSUE THREAD

**Issue by alonalbert** [NineWorlds/serenity-android#305]
I often need to know what episode number I'm watching while one is already playing. I know what the episode name is but not the number, or season number for that matter.

It's rather difficult to do this. I have to go back to the list/grid and check. Depending on how I started playback, there may be extra steps required.

I propose changing the way Title is displayed for episodes. Instead of just the Episode Name, I suggest:

Series Title S##E##: Episode Name

I include the series name here because sometimes, that's not immediately obvious either. The poster may not contain the name of the series, or may even be blank, for obscure series.

I have a change that does this, if you approve, I'll send you a PR.

**Comment by kingargyle** [comment]
Cool.  If you get the PR submitted, I'll make sure it gets merged into the development branch.

**Comment by kingargyle** [comment]
resolved as #306 and scheduled for 1.9.5
