### ISSUE TITLE
Replace Gallery View with DPAD Aware RecyclerView

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#308]
GalleryView is way beyond it's usefulness.  In the move to make a more matrial design and leanback application, need to replace it with the dpad aware exentsion of RecyclerView.

https://github.com/vganin/dpad-aware-recycler-view

**Comment by kingargyle** [comment]
https://github.com/sungerk/GalleryView/blob/master/galleryview/src/main/java/org/net/sunger/widget/GalleryView.java

This provides existing gallery type functionality.

**Comment by Kuro07** [comment]
Great plugin! I was having problems making kodi and plex work together using external players but your application made it possible. I would like to thank you. On another note, may I ask when the next update will be? I've seen you post on the plex forums stating that you'll be updating the app.

**Comment by kingargyle** [comment]
@Kuro07 thanks.. It all depends on my availability to work on it.   I work on it when I have time, which comes in short spurts.   Refactoring to Recycler Views was taking longer than I had anticipated.

**Comment by Kuro07** [comment]
I see. Is there anything that I can help with perhaps?

**Comment by kingargyle** [comment]
@Kuro07 I'm always willing to take pull requests if you have some android development skills.   You can checkout the branch https://github.com/NineWorlds/serenity-android/tree/dpadaware_recycler 

Which contains the current work in progress.  I think I have both the main screen, movies, and tv shows migrated over.   Music and Search still need to be migrated.   Also I know that I have multiple tests that are failing.

With that said I should be getting some more time over the next couple of weeks to get back to this but any pull requests would be appreciated.  

The dpadrecycler-view branch should work with the latest Intellij Community edition.  I haven't migrated yet to gradle (it is on the list).

**Comment by kingargyle** [comment]
This portion is mostly done.   I did end up removing the hardly ever used Music library support, mainly.  Also it looks like Google TV support will need to be dropped.  It had a nice run, but too many limitations on library support to make it worth while continuing to support the platform.

With this change, I may need to temporarily drop Tablet support, and just concentrate on D-Pad aware devices.

Should have this merged in later this weekend.

**Comment by kingargyle** [comment]
This has been merged into develop.
