### ISSUE TITLE
Support Plex Signin for Secure Servers

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#311]
Some information finally on this is available here:

http://forums.plex.tv/discussion/129922/how-to-request-a-x-plex-token-token-for-your-app#latest

**Comment by BartokW** [comment]
About a year ago I was working on adding this, but I'd made a weird copy of the PlexApp Rest Library as that's the only piece I was thinking I would need.  I've now done a proper fork, and have copied the basic functionality in (it was working a year ago), but haven't got any tests set up in the fork yet. 

The repo is https://github.com/BartokW/serenity-android if you're interested.  It was an initial make it work style of code, not necessarily well written.

I'll see about getting the tests set up again, and verify that it's still all working in the near future.

**Comment by kingargyle** [comment]
@BartokW if you want to submit a pull request for the functionality I would gladly take a look at it and see if it can be included.

**Comment by kingargyle** [comment]
Need to look at this again, now that the SerenityClient interface can support multiple users logins.  Emby Media Server requires multiple users, and selection of a user profile to use.   So as the client and login screen is now available I'll revisit this after the rest of the emby client is working.  Moving to 2.1.0

**Comment by kingargyle** [comment]
Plex support is eventually planned to be dropped.  All new development and feature support is targeted toward Emby server going forward.  Keeping this open in case anybody wants to contribute or maintain the Plex Client to provide this functionality.   The Emby Client already includes this support, and will continue to be enhanced.

**Comment by kingargyle** [comment]
Plex is no longer support as of 3.0.
