### ISSUE TITLE
Have you considered an F-Droid repository?

### ISSUE THREAD

**Issue by eyedeekay** [NineWorlds/serenity-android#324]
Pretty simple question, have you considered either distributing your application on the official F-Droid repository or hosting your own? Technically Plex is a non-Libre service but the client should be fine for the official repo, and hosting one's own is pretty easy. For now I'm side-loading, but I'd like to see this happen and would be willing to help make it so.

If there's no interest in that here, I'll probably end up hosting my own. I'd like to do so in a way which is most acceptable to the people who have contributed to the project. Is there any particular information besides the obvious you'd like me to add or make note of if I do so?

**Comment by kingargyle** [comment]
I have no problem hosting it on F-Droid.   At least for the 1.9.x series.  I'm in the middle of some major rework on the 2.0.0 series, and that version is only going to be targeting Android TV and Fire TV devices currently.   As I get Milestone's ready for testing, I have no problems releasing those to F-Droid for distribution for that as well.   So feel free to add an entry to F-Droid.  Send me the link so I can share it on the wiki where people can download it.

**Comment by cmotc** [comment]
Awesome, I'll do that.

**Comment by Perflyst** [comment]
Any updates here? Would be great to see this app on F-Droid

**Comment by kingargyle** [comment]
I

**Comment by kingargyle** [comment]
I'll re-open this and see what is involved... The app has changed a bit, and is only targeting TV enabled devices.

**Comment by kingargyle** [comment]
Looking into this further... F-Droid currently doesn't have native Android TV support.   This means you have to side load the app, and then it doesn't appear on the TV as an option.   I may look into contributing the necessary Launcher items for it but at this time.  I'm taking this out of scope for 2.1 but will keep it open pending F-Droid support for Android TV or Fire TV devices.

https://forum.f-droid.org/t/is-an-android-tv-version-planned-for-f-droid-in-the-future/1895

**Comment by kingargyle** [comment]
Probably not happening, side loading can be done with the versions released through github.
