### ISSUE TITLE
Swap DPadAwareRecyclerView for AndroidLeanback HorizontalRow

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#368]
There are a couple of problems with the DPadAwareRecyclerView.

1. It will randomly crash at times with a NullPointerException when trying to set focus on an item.
2. It doesn't work with the standard onClick and onLongClick events so some functionality that was used in the past is no longer able to be added.  This includes setting watched and unwateched status, adding videos to the playback queue, etc.

Make use of the TVRecyclerView, https://github.com/henryblue/TvRecyclerView

**Comment by kingargyle** [comment]
This tutorial can be useful, implement a BrowserFragment with a HorizontalGridview for the presenter.

http://corochann.com/browsefragment-listrow-customization-android-tv-application-hands-on-tutorial-18-705.html

3 Rows for the the GridView, just 1 row for the Detail View.

**Comment by WolfganP** [comment]
Seems like a good approach @kingargyle. Let me know if you have a prototype and want me to test i on my current setup.

**Comment by kingargyle** [comment]
@WolfganP will do.  I probably won't get to this until sometime next week, have a presentation I need to prepare for  this weekend.

**Comment by kingargyle** [comment]
@WolfganP  what device do you have.  I did some experiments with the leanback implementation and I'm not sure it is going to solve your particular issue with the focus.  I'm probably going to need to buy a device so I can test with it.

**Comment by WolfganP** [comment]
@kingargyle I'm testing in a cheap box with a Mediatek MT8685 SoC (Cortex-A7 Quad core 28nm with neon, GPU Mali 450 MP4) 4 GB eMMC Flash, SDRAM 1 GB DDR3, Ethernet, WiFi, 2xUSB flashed with Android 4.4 (similar to a Xiaomi Mi Box mini).

But there's no need for you to buy such an underpowered box just for testing, just create a debug version of your app and I'll test and collect logs for you. Thx for the effort!

**Comment by kingargyle** [comment]
@WolfganP I'll add a bit of debugging logic to the main screen, and the TV Shows and Series screens, to see which views have Focus when the those Activities are created.   I experienced a similar focus issue when I did some testing of the Leanback library... So I need to at least log, which View on the Screen is getting Focus at different times.

**Comment by kingargyle** [comment]
Continuing to look at this further.  It looks like the horizontal gridview contains an onChildViewSelectedListener which is fired when a child gains the selection focus.  The horizontal grid view uses the GridLayoutManager from leanback which fires this event.    So with this we may be able to emulate the selector implemenation in a more consistent way.  Still need to check to see which views are gaining focus on the Main screen, but this might allow me to replace the main functionality that the DPadaware view was emulating.

**Comment by WolfganP** [comment]
@kingargyle I wonder if you were able to troubleshoot the focus issue with the latest commits somehow? TIA!

**Comment by kingargyle** [comment]
Sorry haven't had much time.  Working on trying to #SaveTheCrew from relocating so haven't had any time to work on Serenity unfortunately.

**Comment by kingargyle** [comment]
Another alternative is the TVRecycerView... still may use Leanback in some spots, but finding out leanback isn't working with Appcompat.

There is a new TVRecyclerView that could be of use, now that I've got the main hurdle done with the Emby Server integration.

**Comment by kingargyle** [comment]
Initial implementation of the TvRecyclerView is happening in Issue #378 this fixes many of the issues I was having with DPadAware RecyclerView.   Closing this issue for the fixes in #378 .
