### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Sogarez** [NineWorlds/serenity-android#370]
It just shows "Unable to connect to Plex Library". Dont find any signs of authorization in settings. Any help?
I'm using "Preferred server address", not discovered servers (my server is not in local network)

**Comment by WolfganP** [comment]
Use any LogCat app to capture the program logs (filter by "serenity"), and post them to help troubleshooting.

**Comment by kingargyle** [comment]
Also, make sure that your server does not sign in automatically to Plex Pass, it is turned on by default.  Unfortunately, Plex has never published an official API to make authorizing easy to do with out doing a lot of reverse engineering.  While I do plan eventually on getting to it, it is lower on my priority list than getting Emby Server integration working.  Emby does provide a nice public and documented API for this.

**Comment by Sogarez** [comment]
Thanks for answers, and yes, it was signing to Plex Pass. All working now, thanks for help!
