### ISSUE TITLE
No option for "Mark as viewed"

### ISSUE THREAD

**Issue by n0v3xx** [NineWorlds/serenity-android#371]
Hi,
in the latest version "v2.0.0-M4" is no option to mark a movie or series as viewed. In 1.9 this was possible.
Can you add it again like the old version?

Thanks

**Comment by kingargyle** [comment]
Yes, this is still a work in progress, as I need to add the longclick support and dialog support back in.

**Comment by kingargyle** [comment]
Moving this to 2.1, I need to re-implement a lot of the context menu options.

**Comment by kingargyle** [comment]
With migration finally to the standard RecyclerView, I can reimplement the context menus.  Need to think how I want things to be displayed, but Watched, Unwatched, Add to Queue, and other missing options will return.

**Comment by kingargyle** [comment]
@n0v3xx This issue should be fixed in 2.0.0-M7 which may be released by the end of next week.  Video watch status can now be toggled again using a long press to bring up the dialog.
