### ISSUE TITLE
Improve Direct Play of Videos

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#415]
Per @CBers comments there needs to be improvements of Direct Playing videos that aren't in an MKV format.  A lot of this is based on the supported contents reported by the device, and probably how Serenity is incorrectly capturing this information.

For videos that are direct playing on Emby or Plex, but not Serenity, then I need the following:

1. Container that the video is using, MKV, VP8, MV4, MP4, etc
2. Video Codec H.264, H.265, MPEG2, etc
3. Audio Codec AC3, DTS, AAC, etc.

These are the main drivers that will affect items.   As Subtitles are re-enabled that will affect items as well.

To help with identifying things, a Debug menu or screen needs to be developed that reports back information regarding what the Device says it supports.

**Comment by kingargyle** [comment]
Okay, it looks like the audio look up isn't detecting that the Shield can support EAC3 audio, so it is falling back to the transcoding option.

I have a couple of ideas on how to improve this, but earliest I'm going to have time to look at it is probably Friday when my Holiday vacation starts.   But this does give me an idea of what is happening at least for the 1080/720 videos.  I'll need to look to see if there is anything else I need to do to get the 4k videos to play with Exoplayer.

**Comment by kingargyle** [comment]
Full List of mimetypes for audio and video files.

https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by CBers** [comment]
No worries David, no rush my end, so enjoy your time off.

**Comment by kingargyle** [comment]
@CBers I did get an NVidia Shield Android TV device over the holidays, so I will get that hooked up to the 4K set I have and see if I can get the app to start direct streaming that content instead of trying to transcode it.

**Comment by kingargyle** [comment]
Sample 4k video content, https://4kmedia.org/

**Comment by kingargyle** [comment]
Tunnelling mode has been enabled.   Will do some work on correctly detecting the video and audio codecs on a device.

**Comment by kingargyle** [comment]
4k content still needs to be addressed, but with the implemenation of #417 the detection of the codecs supported is better.   MKVs and MP4s containers are now direct played..  As well video/audio codecs directly supported on the device.  I cross reference what the server returns as the codecs for the video against what the device says it supports and if it can it direct streams mkvs and mp4s, otherwise it translates to mkv container and aac audio.

**Comment by kingargyle** [comment]
Closing this as NVIDIA Shield and Bravia Android TV devices should have much better direct play of videos starting with version 2.0.7.
