### ISSUE TITLE
Is this client still updated? 

### ISSUE THREAD

**Issue by lsl330** [NineWorlds/serenity-android#451]
Is this client still updated? Can you provide the latest download address, the official plex client is very garbage

**Comment by kingargyle** [comment]
The Client is still being maintained, working on V3 now, but Plex Media Server support is deprecated in favor of Emby Media Server.  Many reasons for this, but mainly lack of a supported client API from Plex as the main one.    V3 isn't publicly available yet.

https://github.com/NineWorlds/serenity-android/releases

Contains all the currently public releases.  Depending on how strict you have your Plex Media Server setup, the versions there might still work with it.  Again, Plex support is no longer actively maintained, and will be dropped when I start released V3 for testing by the public.
